removing non-job pool mode
ess-dmsc/kafka-to-nexus pull request #615
Opened 2021-11-24 09:36 UTC by kmurica

### Issue

ECDC-2619

### Description of work

Removing the non-job pool way to run file writer.

2021-11-24 10:20 UTC, michele-brambilla commented
Can we please discuss this change before proceed to merge?

2021-11-24 15:10 UTC, kmurica commented
> Can we please discuss this change before proceed to merge?

Sure, there are also the ANSTO facility that needs to be inquired.

2021-12-08 18:46 UTC, SkyToGround commented on src/MainOpt.h
> +  uri::URI JobPoolURI{"localhost:9092/kafka-to-nexus.jobpool"};
I would really prefer that you either remove the default address here and/or make the corresponding command line argument required (it has the same effect I believe). You can make the CL argument required on line 137 of "CLIOptions.cpp".

2021-12-08 18:48 UTC, SkyToGround commented on src/MainOpt.h
> +  uri::URI JobPoolURI{"localhost:9092/kafka-to-nexus.jobpool"};
My previous statement was wrong. You have to make the command "required".

2021-12-08 18:49 UTC, SkyToGround requested changes
One minor CLI change is also needed.

2021-12-08 18:52 UTC, SkyToGround commented
One more thing that I forgot: Make the appropriate changes to the documentation and to the "changes.md"-file (maybe under a heading called "Next version" or something similar).

2021-12-08 22:57 UTC, geishm-ansto commented
@kmurica We have used the writer in the job pool mode at Ansto and am comfortable with the change.

2022-01-03 10:07 UTC, merged